---
image:
  name: docker-web.cdek.ru/phnodenx-dev-rocky9-8.2
  entrypoint: ['']

stages:
  - build
  - upload
  - deploy

variables:
  ARTIFACTORY_REPO: "https://repo.cdek.ru/artifactory/erp-cms"
  HTTP_PROXY: "http://runner-proxy.cdek.ru:9000"
  HTTPS_PROXY: "http://runner-proxy.cdek.ru:9000"
  NO_PROXY: "172.16.0.0/16,10.0.0.0/8,192.168.0.0/16,docker,127.0.0.0/8"

build_tag:
  image: docker-proxy.cdek.ru/php:7.4-cli-alpine
  stage: build
  tags:
    - docker
  only:
    - tags
  before_script:
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php');"
    - mv composer.phar /usr/local/bin/composer
    - export RELEASE_VERSION=$(echo "${CI_COMMIT_TAG}" | sed 's/v//')
  script:
    - sed -i "s/\(<version>\)\( *\).*/\1\2${RELEASE_VERSION}<\/version>/" install.xml
    - cd upload/system/library/cdek_official
    - composer i -a
  artifacts:
    name: cdek-integration.ocmod
    paths:
      - upload
      - install.xml

build_custom:
  when: manual
  image: !reference [build_tag, image]
  stage: build
  tags:
    - docker
  artifacts:
    name: cdek-integration.ocmod
    paths:
      - upload
      - install.xml
  before_script:
    - !reference [build_tag, before_script]
    - export RELEASE_VERSION="${CI_COMMIT_REF_NAME}#${CI_COMMIT_SHORT_SHA}"
  script:
    - !reference [build_tag, script]
    - composer i -a --no-dev

upload:
  stage: upload
  tags:
    - docker
  needs:
    - job: build_tag
      artifacts: true
  only:
    - tags
  before_script:
    - export RELEASE_VERSION=$(echo "${CI_COMMIT_TAG}" | sed 's/v//')
    - export ARCHIVE_VERSION=$(echo "${RELEASE_VERSION}" | sed 's/\./_/g')
  script:
    - zip -r cdek.zip upload install.xml
    - curl -u "${NEXUS_LOGIN}":"${NEXUS_PASS}" --upload-file cdek.zip "${ARTIFACTORY_REPO}/$CI_PROJECT_NAME/$CI_COMMIT_BRANCH/wordpress_${ARCHIVE_VERSION}.zip"

release:
  stage: deploy
  tags:
    - docker
  needs:
    - job: upload
  only:
    - tags
  image: registry-gitlab.cdek.ru/gitlab-org/release-cli:latest
  before_script:
    - export RELEASE_VERSION=$(echo "${CI_COMMIT_TAG}" | sed 's/v//')
    - export ARCHIVE_VERSION=$(echo "${RELEASE_VERSION}" | sed 's/\./_/g')
  script:
    - |
      release-cli create --name $CI_COMMIT_TAG --tag-name $CI_COMMIT_TAG \
        --assets-link "{\"name\":\"Архив\",\"filepath\":\"/archive\",
      \"url\":\"${ARTIFACTORY_REPO}$CI_COMMIT_BRANCH/$CI_PROJECT_NAME/opencart_cdek_${ARCHIVE_VERSION}.ocmod.zip\", 
      \"link_type\":\"package\"}" \
