---
image:
  name: docker-web.cdek.ru/phnodenx-dev-rocky8-7.4:7.4.33_16.20.2-20240730_1931-linux-amd64
  entrypoint: ['']

stages:
  - sync
  - build
  - upload
  - deploy

build_tag:
  stage: build
  tags:
    - docker
  only:
    - tags
  before_script:
    - export RELEASE_VERSION=$(echo "${CI_COMMIT_TAG}" | sed 's/v//')
  script:
    - sed -i "s/\(<version>\)\( *\).*/\1\2${RELEASE_VERSION}<\/version>/" install.xml
    - cd upload/system/library/cdek_official
    - composer i -a
  artifacts:
    name: cdek-integration.ocmod
    paths:
      - upload
      - install.xml

build_custom:
  when: manual
  stage: build
  tags:
    - docker
  artifacts:
    name: cdek-integration.ocmod
    paths:
      - upload
      - install.xml
  before_script:
    - !reference [build_tag, before_script]
    - export RELEASE_VERSION="${CI_COMMIT_REF_NAME}#${CI_COMMIT_SHORT_SHA}"
  script:
    - !reference [build_tag, script]
    - composer i -a --no-dev

upload:
  stage: upload
  tags:
    - docker
  needs:
    - job: build_tag
      artifacts: true
  only:
    - tags
  before_script:
    - export RELEASE_VERSION=$(echo "${CI_COMMIT_TAG}" | sed 's/v//')
    - export ARCHIVE_VERSION=$(echo "${RELEASE_VERSION}" | sed 's/\./_/g')
  script:
    - zip -r cdek.zip upload install.xml
    - curl -u "${NEXUS_LOGIN}":"${NEXUS_PASS}" --upload-file cdek.zip "${ARTIFACTORY_REPO}/$CI_PROJECT_NAME/$CI_COMMIT_BRANCH/wordpress_${ARCHIVE_VERSION}.zip"

github:
  image: docker-proxy.cdek.ru/bitnami/git:latest
  stage: sync
  tags:
    - docker
  rules:
    - if: $CI_COMMIT_REF_PROTECTED == "true"
  before_script:
    - git config checkout.defaultRemote origin
    - git remote add -f github "https://${GITHUB_AUTH_USERNAME}:${GITHUB_AUTH_TOKEN}@${GITHUB_REPO}" || true
  script:
    - git branch -D $CI_COMMIT_REF_NAME || true
    - git checkout --track origin/$CI_COMMIT_REF_NAME
    - git pull -f --unshallow
    - git fetch github $CI_COMMIT_REF_NAME
    - git branch -u github/$CI_COMMIT_REF_NAME
    - git push

release:
  stage: deploy
  tags:
    - docker
  needs:
    - job: upload
  only:
    - tags
  image: registry-gitlab.cdek.ru/gitlab-org/release-cli:latest
  before_script:
    - export RELEASE_VERSION=$(echo "${CI_COMMIT_TAG}" | sed 's/v//')
    - export ARCHIVE_VERSION=$(echo "${RELEASE_VERSION}" | sed 's/\./_/g')
  script:
    - |
      release-cli create --name $CI_COMMIT_TAG --tag-name $CI_COMMIT_TAG \
        --assets-link "{\"name\":\"Архив\",\"filepath\":\"/archive\",
      \"url\":\"${ARTIFACTORY_REPO}$CI_COMMIT_BRANCH/$CI_PROJECT_NAME/opencart_cdek_${ARCHIVE_VERSION}.ocmod.zip\", 
      \"link_type\":\"package\"}" \
