version: '3.9'

services:
  app:
    build: .
    volumes:
      - ./upload:/var/www/html
    ports:
      - 8080:80
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 321
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
